name: Doodlyk
favicon: null
layout_spectrum: 0.21073506865650415
typography_spectrum: 0.6857505198568106
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#da272a'
    - '#49484d'
    - '#cbcac8'
  brandStrength: 0.9724519348237664
  lightness: 0.8397509269416332
  saturation: 0.6857222544495016
  rhythmicContrast: 0.8233662825077772
purpose: []
